### ISSUE TITLE
Exit gracefully after "Failed to initialize the application's saved data"

### ISSUE THREAD

**Issue by srilatha-sriram** [vipin1006/eHire#2]
Exit gracefully after "Failed to initialize the application's saved data"

Currently, it is hanging. It is not a good user experience.

**Comment by padalingam87** [comment]
Can you please remove the core data file from Application support folder? Then have a try

**Comment by srilatha-sriram** [comment]
That is not the point. It should exit gracefully.

**Comment by Ajayiosdeveloper** [comment]
Hello Team,
As per searching on this issue i found out that this kind of hanging will be happening only when in development state because of the Core Data model with new changes incompatible with the store already created.This is only for developer convenience and to be fixed during development only.Once we make the model fixed and ready for production.This kind of hanging shall not happen.

Please refer the below link:
http://stackoverflow.com/questions/21323611/core-data-how-to-handle-persistentstorecoordinator-errors-on-first-release

**Comment by srilatha-sriram** [comment]
Thanks for the proper clarification. Closing the issue.
